spring.datasource.url=jdbc:postgresql://localhost:5432/OOP Assignment 3
spring.datasource.username=postgres
spring.datasource.password=12142007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true